### PR TITLE
README.md: improve grammar, structure and add crux install instructions.

### PR DESCRIPTION
**Pull request by wildefyr**
Hopefully this will help, I've tried to keep as much as the original readme as possible while cleaning up grammar and the like seeing as (correct me if I'm wrong) you're not a native english speaker.

### CODE REVIEW

**Comment by Nanoseb** [comment]
Thanks a lot!

**Comment by Nanoseb** [comment]
Just a question, why did you change '#' into '$'? 
Isn't # the usual symbol for a root command and $ for a non root one?

**Comment by wildefyr** [comment]
I don't think I've ever seen that distinction before... It might just be simpler to preface commands that need root with sudo, as that'd be more understood on a glance.

**Comment by Nanoseb** [comment]
I have added 'sudo' when needed, but because I don't know crux I haven't edited this section, anyway I am not sure people using this distro need this kind of indication.

**Comment by wildefyr** [comment]
No they certainly do not :D

**Comment by Nanoseb** [comment]
python-psutil is now needed, you may need to update your crux repo

**Comment by wildefyr** [comment]
What new weird and wonderful features have you added? ;)

**Comment by Nanoseb** [comment]
Something to check if telegram-cli is running and the port available see #7, I thought this lib was by default with python core but it seems it is not. I really don't like adding dependencies when it is not needed, so when I will have more time I will probably look for something else, but still it is the most clever way to check that.

**Pull request merged**
